import { Category } from '@/types/category';

export const DEFAULT_CATEGORIES: Category[] = [
  // Danh mục Chi tiêu (Expense)
  {
    id: 'cat-exp-food',
    name: 'Ăn uống',
    type: 'expense',
    icon: 'Utensils',
    color: '#E67E22',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-transport',
    name: 'Đi lại',
    type: 'expense',
    icon: 'Bus',
    color: '#3498DB',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-shopping',
    name: 'Mua sắm',
    type: 'expense',
    icon: 'ShoppingBag',
    color: '#9B59B6',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-entertainment',
    name: 'Giải trí',
    type: 'expense',
    icon: 'Gamepad2',
    color: '#E74C3C',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-bills',
    name: 'Hóa đơn',
    type: 'expense',
    icon: 'Receipt',
    color: '#1ABC9C',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-health',
    name: 'Sức khỏe',
    type: 'expense',
    icon: 'HeartPulse',
    color: '#2ECC71',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-education',
    name: 'Giáo dục',
    type: 'expense',
    icon: 'GraduationCap',
    color: '#F39C12',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-home',
    name: 'Nhà cửa',
    type: 'expense',
    icon: 'Home',
    color: '#D35400',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-exp-other',
    name: 'Khác',
    type: 'expense',
    icon: 'MoreHorizontal',
    color: '#7F8C8D',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },

  // Danh mục Thu nhập (Income)
  {
    id: 'cat-inc-salary',
    name: 'Lương',
    type: 'income',
    icon: 'Banknote',
    color: '#27AE60',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-inc-bonus',
    name: 'Thưởng',
    type: 'income',
    icon: 'Award',
    color: '#F1C40F',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-inc-freelance',
    name: 'Freelance',
    type: 'income',
    icon: 'Laptop',
    color: '#2980B9',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-inc-investment',
    name: 'Đầu tư',
    type: 'income',
    icon: 'TrendingUp',
    color: '#8E44AD',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-inc-other',
    name: 'Khác',
    type: 'income',
    icon: 'MoreHorizontal',
    color: '#95A5A6',
    isDefault: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
